const API='https://aqanuwilmvdtlzuqlrau.supabase.co/functions/v1/mschool-api/workstation/';
const $=id=>document.getElementById(id);
const PAIR_KEY='mplus_enrollment_device';
let session=null,selected=null,photo=null,stream=null,models=null,lastActivity=Date.now(),lastHeartbeat=0;
function message(text=''){$('message').textContent=text;}
function stopCamera(){stream?.getTracks().forEach(t=>t.stop());stream=null;$('video').srcObject=null;$('video').hidden=true;$('capture').hidden=true;}
function clearPhoto(){if(photo?.url)URL.revokeObjectURL(photo.url);photo=null;$('preview').hidden=true;$('preview').removeAttribute('src');$('save').disabled=true;}
async function api(route,{method='GET',body,admin=false,binary=false}={}){
 const controller=new AbortController(),timeout=setTimeout(()=>controller.abort(),20000);
 try{
  const headers=admin?{'x-mschool-session':localStorage.getItem('mplus_mschool_session')||''}:session?{'x-enrollment-session':session}:{};
  if(body!==undefined)headers['content-type']=binary?body.type:'application/json';
  const response=await fetch(API+route,{method,headers,body:body===undefined?undefined:binary?body:JSON.stringify(body),signal:controller.signal,cache:'no-store'});
  const data=await response.json();
  if(!response.ok){if(response.status===401&&session&&!admin)await lock(false);throw new Error(data.error||'操作未完成，請稍後重試。');}
  return data;
 }catch(e){if(e.name==='AbortError')throw new Error('連線逾時，請檢查網路後再試。');throw e;}finally{clearTimeout(timeout);}
}
function action(id,fn){$(id).addEventListener($(id).tagName==='FORM'?'submit':'click',async event=>{event.preventDefault();const buttons=[...$(id).querySelectorAll('button')];if($(id).tagName==='BUTTON')buttons.push($(id));const states=buttons.map(b=>b.disabled);buttons.forEach(b=>b.disabled=true);message();try{await fn(event);}catch(e){message(e.message||'操作未完成，請再試一次。');}finally{buttons.forEach((b,i)=>b.disabled=states[i]);if(id==='student-form')$('save').disabled=!photo;}});}
async function lock(returnHome=true){const previous=session;session=null;stopCamera();clearPhoto();$('workspace').hidden=true;$('locked').hidden=false;$('student-form').hidden=true;$('students').replaceChildren();$('password').value='';if(previous){fetch(API+'logout',{method:'POST',headers:{'x-enrollment-session':previous},keepalive:true}).catch(()=>{});}
 if(returnHome)location.replace('./');
}
function pairedHint(){$('pair-hint').textContent=localStorage.getItem(PAIR_KEY)?'工作站已配對。請輸入專用密碼開始學生建檔。':'此瀏覽器尚未啟用，請管理同工先設定工作站。';}
async function loadStudents(){const data=await api('students?search='+encodeURIComponent($('search').value));$('students').replaceChildren();if(!data.length){const p=document.createElement('p');p.textContent='沒有找到學生，可確認姓名或新增學生。';$('students').append(p);}for(const student of data){const b=document.createElement('button');b.type='button';b.className='student';if(student.avatar_url&&/^https:\/\//.test(student.avatar_url)){const img=document.createElement('img');img.src=student.avatar_url;img.alt='';b.append(img);}const label=document.createElement('span');label.textContent=student.name;const detail=document.createElement('small');detail.textContent=student.id+' · '+(student.has_face?'已建檔':'尚未拍照');label.append(detail);b.append(label);b.addEventListener('click',()=>editStudent(student));$('students').append(b);}}
function editStudent(student=null){stopCamera();clearPhoto();selected=student;$('name').value=student?.name||'';$('school').value=student?.school||'';$('grade').value=student?.grade||'';$('form-title').textContent=student?'更新學生照片':'新增學生';$('student-form').hidden=false;$('success').hidden=true;$('name').focus();}
function withTimeout(promise,ms,label){return Promise.race([promise,new Promise((_,reject)=>setTimeout(()=>reject(new Error(label)),ms))]);}
async function loadModels(){if(!window.faceapi)throw new Error('辨識工具尚未載入，請稍後重試。');if(!models){const base='https://cdn.jsdelivr.net/npm/@vladmandic/face-api@1.7.15/model/';models=withTimeout(Promise.all([faceapi.nets.tinyFaceDetector.loadFromUri(base),faceapi.nets.faceLandmark68TinyNet.loadFromUri(base),faceapi.nets.faceRecognitionNet.loadFromUri(base)]),45000,'人臉辨識模型載入逾時，請再試一次。').catch(e=>{models=null;throw e;});}await models;}
action('unlock-form',async()=>{const pair=localStorage.getItem(PAIR_KEY);if(!pair)throw new Error('請先由管理同工啟用此瀏覽器。');const data=await api('login',{method:'POST',body:{device_token:pair,password:$('password').value}});session=data.session;lastActivity=Date.now();$('password').value='';$('station-label').textContent=data.station.label;$('locked').hidden=true;$('workspace').hidden=false;$('admin').open=false;await loadStudents();});
action('search-form',loadStudents);action('new',()=>editStudent());action('cancel',()=>{stopCamera();clearPhoto();$('student-form').hidden=true;});
action('camera',async()=>{stopCamera();message('正在準備相機與人臉辨識…');await loadModels();if(!session)throw new Error('請重新解鎖工作站。');if(!navigator.mediaDevices?.getUserMedia)throw new Error('此瀏覽器無法使用相機，請使用支援相機的瀏覽器。');try{const pending=navigator.mediaDevices.getUserMedia({video:{facingMode:'user',width:{ideal:640},height:{ideal:480}},audio:false});let expired=false;const guarded=pending.then(s=>{if(expired||!session){s.getTracks().forEach(t=>t.stop());throw new Error('相機已取消。');}return s;});try{stream=await withTimeout(guarded,30000,'相機尚未授權，請確認瀏覽器相機權限。');}catch(e){expired=true;throw e;}$('video').srcObject=stream;$('video').hidden=false;await $('video').play();$('capture').hidden=false;message('請讓一位學生正面看向鏡頭。');}catch(e){stopCamera();throw new Error(e.name==='NotAllowedError'?'相機權限尚未開啟，請允許相機後重試。':e.message);}});
action('capture',async()=>{const video=$('video'),canvas=$('canvas');if(!video.videoWidth)throw new Error('相機尚未就緒，請稍後再拍。');canvas.width=video.videoWidth;canvas.height=video.videoHeight;canvas.getContext('2d').drawImage(video,0,0);const faces=await withTimeout(faceapi.detectAllFaces(canvas,new faceapi.TinyFaceDetectorOptions({scoreThreshold:.5})).withFaceLandmarks(true).withFaceDescriptors(),15000,'辨識逾時，請重新拍照。');if(!session)return;if(faces.length!==1)throw new Error(faces.length?'畫面有多個人，請只留一位學生再拍照。':'沒有辨識到清楚的人臉，請調整光線再拍照。');const descriptor=Array.from(faces[0].descriptor);if(descriptor.length!==128||descriptor.some(v=>!Number.isFinite(v)||Math.abs(v)>10))throw new Error('人臉資料不完整，請重新拍照。');const blob=await new Promise(resolve=>canvas.toBlob(resolve,'image/jpeg',.88));if(!blob)throw new Error('照片處理失敗，請重新拍照。');clearPhoto();photo={blob,descriptor,requestId:crypto.randomUUID(),url:URL.createObjectURL(blob)};$('preview').src=photo.url;$('preview').hidden=false;$('save').disabled=false;stopCamera();message('照片已準備好，請確認姓名與照片後儲存。');});
action('student-form',async()=>{if(!photo)throw new Error('請先拍照。');const snapshot=photo;const upload=snapshot.upload||await api('upload',{method:'POST',body:snapshot.blob,binary:true});snapshot.upload=upload;if(!session)return;const saved=await api('students',{method:'POST',body:{id:selected?.id||null,name:$('name').value.trim(),school:$('school').value.trim(),grade:$('grade').value.trim(),avatar_url:upload.storageRef,face_descriptor:snapshot.descriptor,request_id:snapshot.requestId}});stopCamera();clearPhoto();$('student-form').hidden=true;$('success').hidden=false;$('saved-student').textContent=saved.name+' · '+saved.id+'，照片與人臉資料已儲存。';message('學生建檔已完成。');await loadStudents();});
for(const id of ['lock','finish'])action(id,()=>lock());action('continue',()=>{$('success').hidden=true;message('請選擇下一位學生，或新增學生。');});
async function loadDevices(){const data=await api('devices',{admin:true});$('admin-settings').hidden=false;$('devices').replaceChildren();for(const d of data){const row=document.createElement('div'),label=document.createElement('strong');label.textContent=d.label+' · '+(d.is_active?'已啟用':'已停用');row.append(label);const toggle=document.createElement('button');toggle.type='button';toggle.className='secondary';toggle.textContent=d.is_active?'停用設備':'重新啟用';toggle.onclick=async()=>{toggle.disabled=true;try{await api('devices',{method:'POST',admin:true,body:{id:d.id,label:d.label,is_active:!d.is_active}});await loadDevices();message('設備設定已更新；原有建檔登入已失效。');}catch(e){message(e.message);}finally{toggle.disabled=false;}};row.append(toggle);const reset=document.createElement('form');const password=document.createElement('input');password.type='password';password.minLength=12;password.maxLength=128;password.required=true;password.autocomplete='new-password';password.setAttribute('aria-label',d.label+'的新專用密碼');password.placeholder='新專用密碼，至少 12 個字元';const save=document.createElement('button');save.textContent='重設專用密碼';save.className='secondary';reset.append(password,save);reset.onsubmit=async e=>{e.preventDefault();save.disabled=true;try{await api('devices',{method:'POST',admin:true,body:{id:d.id,label:d.label,is_active:d.is_active,password:password.value}});password.value='';message('密碼已重設，請用新密碼重新解鎖。');}catch(e){message(e.message);}finally{save.disabled=false;}};row.append(reset);$('devices').append(row);}}
action('load-devices',loadDevices);action('device-form',async()=>{if($('device-password').value!==$('device-confirm').value)throw new Error('兩次密碼不一致。');if(localStorage.getItem(PAIR_KEY))throw new Error('此瀏覽器已配對。請在已啟用設備中重設密碼，或由管理員停用舊設備並清除瀏覽器資料後重新啟用。');const data=await api('devices',{method:'POST',admin:true,body:{label:$('device-name').value,password:$('device-password').value,is_active:true}});localStorage.setItem(PAIR_KEY,data.device_token);$('device-password').value='';$('device-confirm').value='';localStorage.removeItem('mplus_mschool_session');localStorage.removeItem('mplus_current_user');$('admin-settings').hidden=true;$('admin').open=false;pairedHint();message('此瀏覽器已啟用，課輔管理登入已登出。請確認教會 OS 也已登出，再交給建檔同工使用專用密碼。');});
for(const name of ['pointerdown','keydown','input'])document.addEventListener(name,()=>{if(!session)return;lastActivity=Date.now();if(lastActivity-lastHeartbeat>60000){lastHeartbeat=lastActivity;api('session',{method:'POST',body:{}}).catch(e=>message(e.message));}},{passive:true});
setInterval(()=>{if(session&&Date.now()-lastActivity>=15*60*1000)lock();},5000);
document.addEventListener('visibilitychange',()=>{if(document.hidden)stopCamera();else if(session&&Date.now()-lastActivity>=15*60*1000)lock();});
window.addEventListener('pagehide',()=>{stopCamera();if(session){fetch(API+'logout',{method:'POST',headers:{'x-enrollment-session':session},keepalive:true}).catch(()=>{});session=null;}});
pairedHint();
