import test from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';import {fixture} from './helpers/school-db.mjs';
const migration=await readFile(new URL('../supabase/migrations/20261009101537_school_attendance_hours.sql',import.meta.url),'utf8');
async function scenario(fn){const {db}=await fixture();try{await db.exec(`
create table mschool.check_in_logs(id bigint generated always as identity primary key,check_time timestamptz,target_id text,target_name text,role text,action_text text);
create table mschool.points_logs(id bigint generated always as identity primary key,change_time timestamptz,target_id text,target_name text,points_delta integer,reason text);
create table mschool.schedules(id bigint generated always as identity primary key,date date,worker_id text,worker_name text,shift text,hours numeric,job_desc text,role_type text,actual_checkin timestamptz,actual_checkout timestamptz,hourly_wage integer);
`);await db.exec(migration);const punch=async(id='P-QA')=>(await db.query('select mschool.kiosk_checkin($1) result',[id])).rows[0].result;
const report=async(month='2026-09-01',actor='1'.repeat(64))=>(await db.query('select public.school_workhours_report($1,$2) result',[actor,month])).rows[0].result;
const log=async(id,date,action,role='工讀生')=>db.query('insert into mschool.check_in_logs(check_time,target_id,target_name,role,action_text) values($1,$2,$2,$3,$4)',[date,id,role,action]);await fn({db,punch,report,log});}finally{await db.close();}}
test('student gets exactly one daily attendance and one point; repeat cannot become checkout',()=>scenario(async({punch,db})=>{assert.equal((await punch('S-QA')).kind,'student');for(let i=0;i<4;i++)assert.equal((await punch('S-QA')).code,'already');assert.equal((await db.query("select count(*) n from mschool.check_in_logs where target_id='S-QA'")).rows[0].n,1);assert.equal((await db.query('select count(*) n from mschool.points_logs')).rows[0].n,1);assert.equal((await db.query("select points from mschool.users where id='S-QA'")).rows[0].points,1);}));
test('staff first punch is clock-in, immediate repeat denied, second is checkout, third denied',()=>scenario(async({punch,db})=>{const first=await punch();assert.match(first.title,/上班/);assert.equal(first.actual_hours,null);assert.equal((await punch()).code,'too_soon');await db.exec("update mschool.check_in_logs set check_time=now()-interval '61 seconds'");const second=await punch();assert.match(second.title,/下班/);assert.ok(Number(second.actual_seconds)>=61);assert.equal((await punch()).code,'already_completed');assert.equal((await db.query('select count(*) n from mschool.check_in_logs')).rows[0].n,2);assert.equal((await db.query('select count(*) n from mschool.points_logs')).rows[0].n,0);}));
test('unmatched or malformed historical staff cards require review, never invent another card',()=>scenario(async({punch,db})=>{await db.exec("insert into mschool.check_in_logs(check_time,target_id,role,action_text) values(now()-interval '61 seconds','P-QA','工讀生','下班簽退')");assert.equal((await punch()).code,'needs_review');await db.exec("insert into mschool.check_in_logs(check_time,target_id,role,action_text) values(now(),'P-QA','工讀生','下班簽退')");assert.equal((await punch()).code,'needs_review');assert.equal((await db.query('select count(*) n from mschool.check_in_logs')).rows[0].n,2);}));
test('monthly actual hours come from Taipei clock pairs, distinct from scheduled hours and students',()=>scenario(async({log,report,db})=>{await log('P-QA','2026-09-10T01:00:00Z','上班簽到');await log('P-QA','2026-09-10T04:30:00Z','下班簽退');await log('S-QA','2026-09-10T01:00:00Z','+1 點 (到班)','學生');await db.exec("insert into mschool.schedules(date,worker_id,worker_name,role_type,hours,hourly_wage) values('2026-09-10','P-QA','Synthetic','工讀生',7,250)");const r=await report();assert.equal(r.days.length,1);assert.equal(Number(r.days[0].actual_hours),3.5);assert.equal(Number(r.summary[0].planned_hours),7);assert.equal(Number(r.summary[0].actual_seconds),12600);assert.equal(r.days[0].status,'已完成');}));
test('missing, duplicate, reversed cards and schedules without clocks stay pending, not zero',()=>scenario(async({log,report,db})=>{await log('P-QA','2026-09-01T01:00Z','上班簽到');await log('P-QA','2026-09-02T04:00Z','下班簽退');await log('P-QA','2026-09-03T01:00Z','上班簽到');await log('P-QA','2026-09-03T04:00Z','下班簽退');await log('P-QA','2026-09-03T05:00Z','下班簽退');await log('P-QA','2026-09-04T04:00Z','上班簽到');await log('P-QA','2026-09-04T01:00Z','下班簽退');await db.exec("insert into mschool.schedules(date,worker_id,worker_name,hours) values('2026-09-05','P-QA','Synthetic',4)");const r=await report();assert.equal(r.days.length,5);assert.ok(r.days.every(d=>d.actual_hours===null&&d.actual_seconds===null));assert.equal(r.summary[0].actual_hours,null);assert.equal(r.summary[0].pending_days,5);assert.match(r.days[0].status,/下班/);assert.match(r.days[1].status,/上班/);}));
test('monthly Taipei boundaries include UTC previous date and exclude next local month; cross-midnight needs review',()=>scenario(async({log,report})=>{await log('P-QA','2026-08-31T16:30Z','上班簽到');await log('P-QA','2026-08-31T18:00Z','下班簽退');await log('P-QA','2026-09-30T15:00Z','上班簽到');await log('P-QA','2026-09-30T16:30Z','下班簽退');const sep=await report();assert.equal(sep.days[0].day,'2026-09-01');assert.equal(Number(sep.summary[0].actual_hours),1.5);assert.equal(sep.days[1].actual_hours,null);const oct=await report('2026-10-01');assert.equal(oct.days[0].day,'2026-10-01');assert.equal(oct.days[0].actual_hours,null);}));
test('sum exact durations before rounding, future plans are not missing punches, and leap month is valid',()=>scenario(async({log,report,db})=>{for(const day of ['01','02','03']){await log('P-QA',`2026-09-${day}T01:00:00Z`,'上班簽到');await log('P-QA',`2026-09-${day}T01:01:00Z`,'下班簽退');}const r=await report();assert.equal(Number(r.summary[0].actual_hours),.05);await db.exec("insert into mschool.schedules(date,worker_id,hours) values('2099-02-28','P-QA',3)");const future=await report('2099-02-01');assert.equal(future.days[0].status,'尚未到班日');assert.equal(future.summary[0].pending_days,0);assert.deepEqual((await report('2028-02-01')).days,[]);}));
test('workhours report requires a current manager, and RPCs remain unavailable to browser roles',()=>scenario(async({report,db})=>{for(const actor of ['2'.repeat(64),'3'.repeat(64),'f'.repeat(64)])await assert.rejects(report('2026-09-01',actor),/school_access_denied/);for(const role of ['anon','authenticated'])for(const signature of ['public.school_workhours_report(text,date)','mschool.kiosk_checkin(text)'])assert.equal((await db.query('select has_function_privilege($1,$2,$3) ok',[role,signature,'EXECUTE'])).rows[0].ok,false);await assert.rejects(report(null),/invalid_month/);}));
