import test from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';import {randomUUID} from 'node:crypto';import {fixture} from './helpers/school-db.mjs';
const migration=await readFile(new URL('../supabase/migrations/20261009113711_school_daily_data_integrity.sql',import.meta.url),'utf8');
const attendance=await readFile(new URL('../supabase/migrations/20261009101537_school_attendance_hours.sql',import.meta.url),'utf8');
async function scenario(fn){const f=await fixture();const {db}=f;try{await db.exec(`
create table mschool.roll_calls(id bigint generated always as identity primary key,created_at timestamptz default now(),course_name text default '課後輔導',student_id text not null,student_name text not null,attendance_status text,homework_status text,contact_book_signed text,note text);
create table mschool.points_logs(id bigint generated always as identity primary key,change_time timestamptz default now(),target_id text,target_name text,points_delta integer,reason text);
create table mschool.check_in_logs(id bigint generated always as identity primary key,check_time timestamptz,target_id text,target_name text,role text,action_text text);
create table mschool.schedules(id bigint generated always as identity primary key,date date,worker_id text,worker_name text,shift text,hours numeric,job_desc text,role_type text,actual_checkin timestamptz,actual_checkout timestamptz,hourly_wage integer);
insert into mschool.roll_calls(created_at,student_id,student_name) values('2026-09-01T09:00Z','MISSING','Legacy orphan'),('2026-09-01T16:00Z','S-QA','Old 1'),('2026-09-01T16:00Z','S-QA','Old 2');
`);await db.exec(attendance);await db.exec(migration);const rpc=async(name,args)=>(await db.query(`select public.${name}(${args.map((_,i)=>'$'+(i+1)).join(',')}) result`,args)).rows[0].result;
await fn({...f,rpc});}finally{await db.close();}}
const actor='1'.repeat(64),teacher='2'.repeat(64),reader='3'.repeat(64);
const row={student_id:'S-QA',attendance_status:'出席',homework_status:'已完成',contact_book_signed:'是',note:''};
const schedule={date:'2026-10-12',worker_id:'P-QA',shift:'16:00 - 18:00',hourly_wage:190,job_desc:'Synthetic'};
test('additive migration preserves mixed legacy dates, duplicates, orphans and private permissions',()=>scenario(async({db,rpc})=>{assert.equal((await db.query('select count(*) n from mschool.roll_calls where class_date is null')).rows[0].n,3);const r=await rpc('school_rollcall_read',[actor,'2026-09-01','2026-09-01','課後輔導']);assert.equal(r.records.length,3);assert.equal(r.records[0].date_basis,'legacy_review');assert.equal(r.revision,'0');for(const name of ['school_save_rollcall(text,date,text,jsonb,text,uuid)','school_adjust_points(text,text,integer,text,uuid)','school_mutate_schedules(text,text,bigint,jsonb,uuid,boolean)','school_import_rows(text,jsonb,uuid)','school_kiosk_gate(text,text,text)','school_mutate_users_core(text,text,text,jsonb,boolean)'])for(const role of ['anon','authenticated'])assert.equal((await db.query('select has_function_privilege($1,$2,$3) ok',[role,'public.'+name,'EXECUTE'])).rows[0].ok,false);}));
test('rollcall save updates only highest legacy record; explicit day and actual record time; stale revision rejected; retry idempotent',()=>scenario(async({db,rpc})=>{const request=randomUUID(),args=[actor,'2026-09-01','課後輔導',[row],'0',request];assert.equal((await rpc('school_save_rollcall',args)).revision,'1');assert.equal((await rpc('school_save_rollcall',args)).revision,'1');assert.equal((await db.query('select count(*) n from mschool.roll_calls')).rows[0].n,3);await assert.rejects(rpc('school_save_rollcall',[...args.slice(0,5),randomUUID()]),/rollcall_conflict/);await rpc('school_save_rollcall',[teacher,'2026-10-12','課後輔導',[row],'0',randomUUID()]);const r=(await db.query("select * from mschool.roll_calls where class_date='2026-10-12'")).rows[0];assert.equal(r.student_name,'Synthetic Student');assert.ok(r.recorded_at);assert.equal(r.recorded_by,'T-QA');assert.equal(r.created_at.toISOString(),'2026-10-12T16:00:00.000Z');await assert.rejects(rpc('school_save_rollcall',[reader,'2026-10-12','課後輔導',[row],'1',randomUUID()]),/school_access_denied/);await assert.rejects(rpc('school_save_rollcall',[actor,'2026-10-13','課後輔導',[row,row],'0',randomUUID()]),/duplicate_student/);}));
test('atomic points, replay, no negative balance and stale profiles cannot overwrite; opening entries only for new people',()=>scenario(async({db,rpc,mutate})=>{await db.exec("update mschool.users set points=10 where id='S-QA'");const args=[actor,'S-QA',2,'Synthetic award',randomUUID()];assert.equal((await rpc('school_adjust_points',args)).balance,12);assert.equal((await rpc('school_adjust_points',args)).balance,12);await rpc('school_adjust_points',[teacher,'S-QA',-3,'Correction',randomUUID()]);await assert.rejects(rpc('school_adjust_points',[actor,'S-QA',-10,'No',randomUUID()]),/invalid_points_balance/);await assert.rejects(mutate({payload:{points:10}}),/use_points_ledger/);await mutate({payload:{name:'Renamed'}});assert.equal((await db.query("select points from mschool.users where id='S-QA'")).rows[0].points,9);assert.equal((await rpc('school_points_history',[reader,'S-QA'])).length,2);await mutate({method:'POST',id:null,payload:{id:'S-NEW',name:'New',points:5}});assert.equal((await db.query("select count(*) n from mschool.points_logs where source='opening'")).rows[0].n,1);await assert.rejects(rpc('school_adjust_points',[reader,'S-QA',1,'Denied',randomUUID()]),/school_access_denied/);}));
test('checkin eligibility matches students, active workers, retired/unknown roles; attendance ledger remains one per day',()=>scenario(async({db})=>{for(const [role,status,expected] of [['學生','在班',true],['學生','畢業',false],['學生','退班',false],['老師','在職',true],['工讀生','離職',false],['other','在班',false],[null,null,true]])assert.equal((await db.query('select mschool.person_can_checkin($1,$2) ok',[role,status])).rows[0].ok,expected);await db.exec("update mschool.users set status='畢業' where id='S-QA'");assert.equal((await db.query("select mschool.kiosk_checkin('S-QA') result")).rows[0].result.code,'not_eligible');await db.exec("update mschool.users set status='在班' where id='S-QA'");await db.query("select mschool.kiosk_checkin('S-QA')");await db.query("select mschool.kiosk_checkin('S-QA')");assert.equal((await db.query("select count(*) n from mschool.points_logs where source='attendance'")).rows[0].n,1);}));
test('schedule preview is read only, adjacent overnight overlaps block atomically, endpoints may touch, repeated saves replay',()=>scenario(async({db,rpc})=>{const id=randomUUID();let args=[actor,'POST',null,[schedule],id,true];assert.equal((await rpc('school_mutate_schedules',args)).ok,true);assert.equal((await db.query('select count(*) n from mschool.schedules')).rows[0].n,0);args[5]=false;await rpc('school_mutate_schedules',args);await rpc('school_mutate_schedules',args);assert.equal((await db.query('select count(*) n from mschool.schedules')).rows[0].n,1);const overlap={...schedule,shift:'17:00-19:00'};assert.equal((await rpc('school_mutate_schedules',[actor,'POST',null,[overlap],null,true])).ok,false);await assert.rejects(rpc('school_mutate_schedules',[actor,'POST',null,[overlap],randomUUID(),false]),/schedule_conflict/);await rpc('school_mutate_schedules',[actor,'POST',null,[{...schedule,shift:'18:00-20:00'}],randomUUID(),false]);await rpc('school_mutate_schedules',[actor,'POST',null,[{...schedule,date:'2026-10-13',shift:'23:00-02:00'}],randomUUID(),false]);assert.equal((await rpc('school_mutate_schedules',[actor,'POST',null,[{...schedule,date:'2026-10-14',shift:'01:00-03:00'}],null,true])).ok,false);await assert.rejects(rpc('school_mutate_schedules',[teacher,'DELETE',1,[],randomUUID(),false]),/school_access_denied/);await assert.rejects(rpc('school_mutate_schedules',[reader,'POST',null,[schedule],randomUUID(),false]),/school_access_denied/);}));
test('import records partial outcomes, concurrent edits fail without overwrites, retries replay, history excludes source payload',()=>scenario(async({db,rpc})=>{const rows=[{row:2,id:'S-QA',kind:'update',payload:{name:'Updated'},expected:{name:'Synthetic Student'}},{row:3,id:'S-NEW',kind:'insert',payload:{id:'S-NEW',name:'New',role_type:'學生'}},{row:4,id:'S-QA',kind:'update',payload:{name:'Wrong'},expected:{name:'Old'}}];const args=[actor,rows,randomUUID()],r=await rpc('school_import_rows',args);assert.equal(r.success,2);assert.equal(r.results[2].ok,false);assert.deepEqual(await rpc('school_import_rows',args),r);assert.equal((await db.query("select name from mschool.users where id='S-QA'")).rows[0].name,'Updated');const h=await rpc('school_import_history',[actor]);assert.equal(h.length,1);assert.equal(h[0].payload,undefined);await assert.rejects(rpc('school_import_rows',[teacher,rows,randomUUID()]),/school_access_denied/);}));
test('kiosk pairing is optional until acceptance, requires active device for enforcement, revocation denies, bucket limits bounded',()=>scenario(async({rpc,db})=>{const hash='a'.repeat(64),bucket='b'.repeat(64);await assert.rejects(rpc('school_kiosk_manage',[actor,'policy',null,null,null,true]),/active_device_required/);let r=await rpc('school_kiosk_manage',[actor,'register','Synthetic',hash,null,null]);assert.equal(r.require_device,false);assert.equal(r.devices[0].token_hash,undefined);await rpc('school_kiosk_manage',[actor,'policy',null,null,null,true]);assert.equal((await rpc('school_kiosk_gate',[null,bucket,'logs'])).code,'device_required');await db.exec('begin');for(let i=0;i<120;i++)assert.equal((await rpc('school_kiosk_gate',[hash,bucket,'logs'])).ok,true);assert.equal((await rpc('school_kiosk_gate',[hash,bucket,'logs'])).code,'rate_limited');await db.exec('commit');await rpc('school_kiosk_manage',[actor,'revoke',null,null,r.created_id,null]);assert.equal((await rpc('school_kiosk_gate',[hash,bucket,'logs'])).code,'device_required');}));

test('uncertain kiosk punch replays the original result instead of creating a later checkout',()=>scenario(async({rpc,db})=>{const scope='c'.repeat(64),request=randomUUID(),args=[scope,'P-QA',request];const first=await rpc('school_kiosk_punch',args);await db.exec("update mschool.check_in_logs set check_time=now()-interval '61 seconds'");assert.deepEqual(await rpc('school_kiosk_punch',args),first);assert.equal((await db.query('select count(*) n from mschool.check_in_logs')).rows[0].n,1);assert.match((await rpc('school_kiosk_punch',[scope,'P-QA',randomUUID()])).title,/下班/);}));
test('stale preview cannot commit after another schedule claims its interval; a failed batch writes no partial schedule',()=>scenario(async({rpc,db})=>{assert.equal((await rpc('school_mutate_schedules',[actor,'POST',null,[schedule],null,true])).ok,true);await rpc('school_mutate_schedules',[teacher,'POST',null,[schedule],randomUUID(),false]);await assert.rejects(rpc('school_mutate_schedules',[actor,'POST',null,[{...schedule,date:'2026-10-13'},schedule],randomUUID(),false]),/schedule_conflict/);assert.equal((await db.query('select count(*) n from mschool.schedules')).rows[0].n,1);}));

test('photo backfill compares the exact student photo/status and never overwrites a changed or existing face',()=>scenario(async({rpc,db})=>{await db.exec("update mschool.users set avatar_url='mschool-avatar://test.jpg' where id='S-QA'");const args=[actor,'S-QA','mschool-avatar://test.jpg','在班',Array(128).fill(.1)];assert.equal((await rpc('school_backfill_face',[...args.slice(0,2),'old.jpg',...args.slice(3)])).saved,false);assert.equal((await rpc('school_backfill_face',args)).saved,true);assert.equal((await rpc('school_backfill_face',args)).saved,false);await assert.rejects(rpc('school_backfill_face',[teacher,...args.slice(1)]),/school_access_denied/);}));
