import test from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import {readFile} from 'node:fs/promises';import {webcrypto} from 'node:crypto';
const source=await readFile(new URL('../enrollment.mjs',import.meta.url),'utf8');
function harness(){const elements=new Map(),handlers=new Map(),requests=[];const get=id=>{if(!elements.has(id))elements.set(id,{id,tagName:id.endsWith('form')?'FORM':'BUTTON',value:'',textContent:'',hidden:true,disabled:false,videoWidth:480,videoHeight:480,querySelectorAll:()=>[],addEventListener(event,fn){handlers.set(id+':'+event,fn)},getContext:()=>({drawImage(){}}),play:()=>Promise.resolve(),focus(){},removeAttribute(){},replaceChildren(){},append(){}});return elements.get(id);};
 const context=vm.createContext({document:{getElementById:get,addEventListener(){},createElement:()=>({append(){},addEventListener(){}})},window:{addEventListener(){}},localStorage:{getItem:()=>null,removeItem(){},setItem(){}},location:{replace(){}},URL:{createObjectURL:()=> 'blob:synthetic',revokeObjectURL(){}},crypto:webcrypto,AbortController,setTimeout:()=>0,clearTimeout(){},setInterval(){},console,fetch:async(url,options)=>{requests.push({url,options});throw new Error('Blocked unexpected request');}});vm.runInContext(source,context);return {context,elements,get,requests,run:code=>vm.runInContext(code,context),click:id=>handlers.get(id+':'+(id.endsWith('form')?'submit':'click'))({preventDefault(){}})};}
const tick=()=>new Promise(r=>setImmediate(r));
test('workstation cancel while models load never opens a late camera',async()=>{const h=harness();let resolve,calls=0;h.context.wait=new Promise(r=>resolve=r);h.context.navigator={mediaDevices:{getUserMedia(){calls++;}}};h.run("session='synthetic';models=wait;window.faceapi={};editStudent({id:'S1'})");const task=h.click('camera');await tick();await h.click('cancel');resolve();await task;assert.equal(calls,0);assert.equal(h.get('student-form').hidden,true);});
test('workstation late camera authorization stops its tracks after cancel',async()=>{const h=harness();let resolve,stopped=0;h.context.navigator={mediaDevices:{getUserMedia:()=>new Promise(r=>resolve=r)}};h.run("session='synthetic';models=Promise.resolve();window.faceapi={};editStudent({id:'S1'})");const task=h.click('camera');await tick();await h.click('cancel');resolve({getTracks:()=>[{stop(){stopped++}}]});await task;assert.equal(stopped,1);assert.equal(h.get('video').srcObject,null);});
test('workstation a pending face extraction cannot populate a different student',async()=>{const h=harness();let resolve;h.context.wait=new Promise(r=>resolve=r);h.context.faceapi={TinyFaceDetectorOptions:class{},detectAllFaces:()=>({withFaceLandmarks:()=>({withFaceDescriptors:()=>h.context.wait})})};h.run("session='synthetic';editStudent({id:'S1'})");const task=h.click('capture');await tick();h.run("editStudent({id:'S2'})");resolve([{descriptor:Array(128).fill(.1)}]);await task;assert.equal(h.run('photo'),null);assert.equal(h.get('save').disabled,true);assert.equal(h.run('selected.id'),'S2');});
test('workstation cancelled upload never saves old photo against a new student',async()=>{const h=harness();let resolve;h.context.fetch=(url,options)=>{h.requests.push({url,options});return new Promise(r=>resolve=r)};h.run("session='synthetic';editStudent({id:'S1'});photo={blob:{type:'image/jpeg'},descriptor:Array(128).fill(.1),requestId:crypto.randomUUID()}");h.get('name').value='Old Student';const task=h.click('student-form');await tick();h.run("editStudent({id:'S2'})");h.get('name').value='New Student';resolve({ok:true,json:async()=>({storageRef:'mschool-avatar://synthetic'})});await task;assert.equal(h.requests.length,1);assert.match(h.requests[0].url,/upload$/);assert.equal(h.run('selected.id'),'S2');assert.equal(h.get('success').hidden,true);});
