import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {fixture} from './helpers/school-db.mjs';
const migration=await readFile(new URL('../supabase/migrations/20261009093327_school_enrollment_workstation.sql',import.meta.url),'utf8');
const actor='9'.repeat(64),pair='a'.repeat(64),session='b'.repeat(64),credential={salt:'c'.repeat(32),hash:'d'.repeat(64),iterations:600000};
async function scenario(fn){const h=await fixture();const db=h.db;try{await db.exec('create schema storage;create table storage.objects(bucket_id text,name text);');await db.exec(migration);await db.exec(await readFile(new URL('../supabase/migrations/20261009095206_school_station_setup_logout.sql',import.meta.url),'utf8'));const rpc=async(name,args)=>(await db.query(`select public.${name}(${args.map((_,i)=>'$'+(i+1)).join(',')}) result`,args)).rows[0].result;const device=await rpc('school_station_manage',['1'.repeat(64),null,'Synthetic station',true,pair,credential]);assert.equal(await h.resolve(),null);await h.issue(0,actor);await rpc('school_station_login_finish',[pair,1,session]);await fn({db,rpc,device});}finally{await db.close();}}
const savePayload=device=>({name:'Synthetic child',school:'Synthetic school',grade:'三年級',avatar_url:`mschool-avatar://enrollment/${device.id}/${'e'.repeat(64)}.jpg`,face_descriptor:Array(128).fill(.1)});
async function photo(db,p){await db.query('insert into storage.objects values($1,$2)',['mschool-avatars',p.avatar_url.slice(17)]);}
test('station provisioning requires current manager and never exposes pairing hash or password',()=>scenario(async({rpc})=>{await assert.rejects(rpc('school_station_manage',['2'.repeat(64),null,'Bad station',true,pair,credential]),/station_manager_required/);const list=await rpc('school_station_devices',[actor]);assert.equal(list.length,1);assert.deepEqual(Object.keys(list[0]).sort(),['id','is_active','label','updated_at']);for(const bad of [{...credential,salt:null},{...credential,hash:null},{...credential,iterations:1}])await assert.rejects(rpc('school_station_manage',[actor,null,'Invalid station',true,'f'.repeat(64),bad]),/invalid_credential/);}));
test('station search masks contacts, health, face vectors and all staff',()=>scenario(async({rpc,db})=>{await db.exec("update mschool.users set phone='private',health_notes='private' where id='S-QA'");const rows=await rpc('school_station_students',[session,'']);assert.equal(rows.length,1);assert.deepEqual(Object.keys(rows[0]).sort(),['avatar_url','grade','has_face','id','name','school']);}));
test('station creates student, retakes photo and preserves protected data with audit',()=>scenario(async({rpc,db,device})=>{const p=savePayload(device);await photo(db,p);const saved=await rpc('school_station_save',[session,p]);assert.match(saved.id,/^\d{4}S\d{4}$/);await db.query("update mschool.users set points=37,phone='Keep',health_notes='Keep' where id=$1",[saved.id]);await rpc('school_station_save',[session,{...p,id:saved.id,name:'Updated'}]);const row=(await db.query('select * from mschool.users where id=$1',[saved.id])).rows[0];assert.equal(row.points,37);assert.equal(row.phone,'Keep');assert.equal(row.health_notes,'Keep');assert.equal(row.role_type,'學生');assert.equal((await db.query("select count(*) n from mschool.enrollment_audit where event in ('student_created','student_photo_updated')")).rows[0].n,2);}));
test('station rejects staff edits, extra fields, missing/foreign photos and invalid face data',()=>scenario(async({rpc,db,device})=>{const p=savePayload(device);await assert.rejects(rpc('school_station_save',[session,p]),/station_photo_required/);await photo(db,p);await assert.rejects(rpc('school_station_save',[session,{...p,id:'M-QA'}]),/station_student_only/);for(const extra of [{role_type:'同工'},{phone:'unsafe'},{status:'離職'}])await assert.rejects(rpc('school_station_save',[session,{...p,...extra}]),/station_fields_denied/);await assert.rejects(rpc('school_station_save',[session,{...p,avatar_url:p.avatar_url.replace(device.id,'11111111-1111-4111-8111-111111111111')}]),/station_photo_required/);for(const value of [[],Array(128).fill('bad'),Array(128).fill(null),Array(128).fill(100)])await assert.rejects(rpc('school_station_save',[session,{...p,face_descriptor:value}]),/invalid_face/);await db.exec("update mschool.users set status='畢業' where id='S-QA'");await assert.rejects(rpc('school_station_save',[session,{...p,id:'S-QA'}]),/station_student_only/);}));
test('five password attempts rate-limit and device version prevents stale login',()=>scenario(async({rpc,device})=>{for(let i=0;i<5;i++)assert.equal((await rpc('school_station_login_prepare',[pair])).version,1);assert.deepEqual(await rpc('school_station_login_prepare',[pair]),{blocked:true});await rpc('school_station_manage',[actor,device.id,'Synthetic station',true,null,credential]);assert.equal(await rpc('school_station_login_finish',[pair,1,'f'.repeat(64)]),null);assert.equal(await rpc('school_station_session',[session]),null);}));
test('station logout, idle expiry, absolute expiry and remote disable invalidate session',()=>scenario(async({rpc,db,device})=>{await rpc('school_station_logout',[session]);assert.equal(await rpc('school_station_session',[session]),null);await db.exec('update mschool.enrollment_sessions set revoked_at=null,last_seen=now()-interval \'16 minutes\'');assert.equal(await rpc('school_station_session',[session]),null);await db.exec('update mschool.enrollment_sessions set last_seen=now(),expires_at=now()-interval \'1 second\'');assert.equal(await rpc('school_station_session',[session]),null);await db.exec('update mschool.enrollment_sessions set expires_at=now()+interval \'1 hour\'');await rpc('school_station_manage',[actor,device.id,'Synthetic station',false,null,null]);assert.equal(await rpc('school_station_session',[session]),null);assert.equal(await rpc('school_station_login_prepare',[pair]),null);}));
test('public roles cannot read station auth tables or execute station functions',()=>scenario(async({db})=>{for(const role of ['anon','authenticated']){for(const table of ['enrollment_devices','enrollment_sessions','enrollment_audit'])assert.equal((await db.query('select has_table_privilege($1,$2,$3) ok',[role,'mschool.'+table,'SELECT'])).rows[0].ok,false);for(const signature of ['school_station_session(text)','school_station_login_prepare(text)','school_station_save(text,jsonb)'])assert.equal((await db.query('select has_function_privilege($1,$2,$3) ok',[role,'public.'+signature,'EXECUTE'])).rows[0].ok,false);}}));

test('student save request retry returns same result without duplicate students or audit',()=>scenario(async({rpc,db,device})=>{const p={...savePayload(device),request_id:'99999999-9999-4999-8999-999999999999'};await photo(db,p);const first=await rpc('school_station_save',[session,p]);const second=await rpc('school_station_save',[session,p]);assert.deepEqual(second,first);assert.equal((await db.query("select count(*) n from mschool.users where name='Synthetic child'")).rows[0].n,1);assert.equal((await db.query('select count(*) n from mschool.enrollment_audit where request_id=$1',[p.request_id])).rows[0].n,1);}));
